# ==========================================
# CONFIGURACIÓ DEL CURS - PERSONALITZAR
# ==========================================

# Informació acadèmica específica del mòdul (CANVIAR per cada mòdul)
cicle_modulo: "DA2_Optativa"
module_title: "Angular"
authors: 
  - "Ismael Trascastro"

# Informació completa del curs
curs:
  
  unitats:
    - nom: "Unitat 1"
      numero: 1
      descripcio: "Primera unitat del curs"
      blocs:
        - { nom: "Bloc 1", numero: 1, descripcio: "Primer bloc de la unitat 1" }
        - { nom: "Bloc 2", numero: 2, descripcio: "Segon bloc de la unitat 1" }
    - nom: "Unitat 2"
      numero: 2
      descripcio: "Segona unitat del curs"
      blocs:
        - { nom: "Bloc 3", numero: 3, descripcio: "Primer bloc de la unitat 2" }
        - { nom: "Bloc 4", numero: 4, descripcio: "Segon bloc de la unitat 2" }
    - nom: "Unitat 3"
      numero: 3
      descripcio: "Tercera unitat del curs"
      blocs:
        - { nom: "Bloc 5", numero: 5, descripcio: "Primer bloc de la unitat 3" }
        - { nom: "Bloc 6", numero: 6, descripcio: "Segon bloc de la unitat 3" }
    - nom: "Unitat 4"
      numero: 4
      descripcio: "Quarta unitat del curs"
      blocs:
        - { nom: "Bloc 7", numero: 7, descripcio: "Primer bloc de la unitat 4" }
        - { nom: "Bloc 8", numero: 8, descripcio: "Segon bloc de la unitat 4" }

# URLs de desplegament (CANVIAR per cada professor)
url: "https://itrascastro.github.io"                    # La vostra URL de GitHub Pages
baseurl: ""                                             # Portable - funciona en qualsevol carpeta
repository: itrascastro/ioc-da2-optativa-angular        # El vostre repositori GitHub
github:
  username: itrascastro                                 # El vostre usuari GitHub

# ==========================================
# CONFIGURACIÓ JEKYLL - NO TOCAR
# ==========================================

# Informació genèrica IOC (NO CANVIAR)
organization: "Institut Obert de Catalunya"

# Motor de renderitzat
markdown: kramdown
highlighter: rouge

# Configuració SASS
sass:
  sass_dir: _sass
  style: compressed

# Plugins necessaris
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc

# Configuració del tema
theme: minima

# Configuració de col·leccions per les unitats
collections:
  unitats:
    output: true
    permalink: /:collection/:name/

# Configuració Kramdown per millor rendering
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'highlight'
    block:
      line_numbers: true

# Configuració TOC (Table of Contents)
toc:
  min_level: 2
  max_level: 4
  no_toc_section_class: no_toc

# SEO i idioma
lang: ca
locale: ca_ES

# Configuració per desenvolupament local
livereload: true
incremental: true

# Social media (opcional)
twitter_username: IOC_cat
github_username: itrascastro

# Configuració de layouts per defecte
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "unitat-*"
      type: "pages"
    values:
      layout: "bloc"
      sidebar: true
      toc: true

# Exclusions de Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - package*.json